In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__  # q1. checking pandas version

'3.0.5'

In [4]:
data = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
!wget $data

--2026-09-25 17:27:58--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.1’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.08s

2026-09-25 17:27:58 (7.59 MB/s) - ‘car_fuel_efficiency_2026.csv.1’ saved [635180/635180]

In [5]:
df = pd.read_csv(data)  # for looking the data
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.info()  # q2: for checking how many rows of data are there.

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [7]:
df.fuel_type.nunique()  # q3: checking how many unique fuel types are there.

3

In [8]:
df.isnull().sum()  # q4: checking which columns have the missing values

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df[(df.origin == "Asia")].fuel_efficiency_mpg.max() #q5: checking max fuel efficiency of cars from asia.

np.float64(41.2)

In [10]:
horsepower_median = df.horsepower.median()    #q6: checking the median horsepower .
horsepower_median

np.float64(254.0)

In [11]:
# Mode of horspower column (most frequent value)
horsepower_mode=df.horsepower.mode()[0]
horsepower_mode

np.float64(252.0)

In [12]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [13]:
df.horsepower = df.horsepower.fillna(horsepower_mode) # filling the null with mode values

In [14]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [15]:
df.horsepower.median()  # finding the median again to see if the median has changed

np.float64(252.0)

In [19]:
cars_asia = df[df.origin == "Asia"][["vehicle_weight", "model_year"]]  #q7: 1 Selecting all cars from asia and selecting columns vehicle_weight and model_year
cars_asia

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [64]:
X = cars_asia.head(7).to_numpy()  # q7: 3,4 Getting 7 values and converting them to numpy arrays.
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [28]:
X_transpose = X.T   
X_transpose

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [52]:
X_transpose.shape

(2, 7)

In [63]:
XTX = np.dot(X, X_transpose)
XTX

array([[21961616, 22250432, 21921212, 22688888, 20753972, 24173916,
        22897924],
       [22250432, 22544164, 22209324, 22990376, 21022444, 24498332,
        23201348],
       [21921212, 22209324, 21880909, 22646666, 20716479, 24128437,
        22855443],
       [22688888, 22990376, 22646666, 23448884, 21428846, 24992538,
        23662582],
       [20753972, 21022444, 20716479, 21428846, 19630549, 22818647,
        21629633],
       [24173916, 24498332, 24128437, 24992538, 22818647, 26646941,
        25217899],
       [22897924, 23201348, 22855443, 23662582, 21629633, 25217899,
        23878861]])

In [62]:
XTX.shape

(7, 7)

In [61]:
XTX_inverse = np.linalg.pinv(XTX)  # Invert XTX

In [60]:
XTX_inverse.shape

(7, 7)

In [78]:
y = [(1100, 1300, 800, 900, 1000, 1100, 1200)]
y

[(1100, 1300, 800, 900, 1000, 1100, 1200)]

In [80]:
# Multiplication of the inverse of XTX with the transpose of X
X_trans_XTX_inv = np.dot(X_transpose, XTX_inverse) 
X_trans_XTX_inv.shape
#  multiply the result by y to obtain w
w = np.dot(y, X_trans_XTX_inv.T) # replaced positions to match dimensions for multiplication.
w

array([[0.13644777, 0.2327492 ]])

In [81]:
sum_w = np.sum(w)    #sum of all the elements of the result
sum_w

np.float64(0.3691969690492639)